name: hail-xgboost-hailcast
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.1
  - xgboost=1.7
  - scikit-learn=1.3
  - shap=0.43
  - matplotlib=3.8
  - seaborn=0.13
  - pyyaml=6.0
  - netcdf4
  - xarray

